spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.227:3306/mall_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # Redis 配置
  redis:
    host: 192.168.10.227
    port: 6379
    password: root
    database: 0
  # RabbitMQ 配置
  rabbitmq:
    host: 192.168.10.227
    port: 5672
    username: binlog
    password: binlog
