spring:
  # Redis 配置
  redis:
    host: 192.168.10.227
    port: 6379
    password: root
    database: 0

# 验证码配置
captcha:
  # 业务接口配置
  service:
    # 业务实现类
    implementation: easyCaptchaServiceImpl
