spring:
  # Spring Security 安全配置
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取 JWK 公钥接口
          jwk-set-uri: http://192.168.10.227:${server.port}/mall-security/jwk/jwk-set
  # Redis 配置
  redis:
    host: 192.168.10.227
    port: 6379
    password: root
    database: 0
